# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with TypeScript installed
FROM node:22.12-alpine AS builder

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN npm install

# Build the project
RUN npm run build

# Use a minimal Node.js image for production
FROM node:22-alpine AS release

# Set working directory
WORKDIR /app

# Copy built files and package.json
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app/

# Install production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Define entry point
ENTRYPOINT ["node", "dist/index.js"]
